name: Flutter APK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      # 🔥 Recreate Android folder (VERY IMPORTANT)
      - name: Recreate Android files
        run: flutter create . --project-name restaurant_ui_kit

      # 🔥 Clean project
      - name: Clean project
        run: |
          rm -f pubspec.lock
          flutter clean

      # 🔥 Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 🔥 Fix gradlew permission
      - name: Fix gradlew permission
        run: chmod +x android/gradlew

      # 🚀 Build APK
      - name: Build APK
        run: flutter build apk --release

      # 📦 Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      # 🔥 NEW: Upload Android folder (IMPORTANT)
      - name: Upload Android Folder
        uses: actions/upload-artifact@v4
        with:
          name: android-folder
          path: android
